#!/usr/bin/env bash

function find_local_pkgset
{
    local TOPFILE=.gvm_local
    if [ -d "$TOPFILE" ] ; then
        PWD=$(/bin/pwd)
        echo "$PWD"
    else
        local HERE="$PWD"
        T=
        while [ \( ! \( -d "$TOPFILE" \) \) -a \( "$PWD" != "/" \) ]; do
            builtin cd ..
            T=$(/bin/pwd)
        done
        builtin cd "$HERE"
        if [ -d "$T/$TOPFILE" ]; then
            echo "$T"
        fi
    fi
}
